Feat/socket frontend
Michi4/LuminAI pull request #55
Opened 2023-12-13 10:14 UTC by Michi4

2023-12-13 13:31 UTC, Stenz123 requested changes

2023-12-13 13:31 UTC, Stenz123 commented on LuminAi/src/main/resources/drivers/energy_data.json
> -  "devices": [
Do we still need this file?

2023-12-13 13:31 UTC, Stenz123 commented on LuminAi/src/main/frontend/src/services/PowerService.js
> +const socket = new WebSocket('ws://localhost:8080/subscribeUpdates');
please add this to the properties

2023-12-13 13:35 UTC, Michi4 commented on LuminAi/src/main/resources/drivers/energy_data.json
> -  "devices": [
yes

2023-12-15 07:46 UTC, Michi4 commented on LuminAi/src/main/frontend/src/services/PowerService.js
> +const socket = new WebSocket('ws://localhost:8080/subscribeUpdates');
67aabeb

2023-12-18 09:08 UTC, Stenz123 approved these changes

2023-12-18 09:08 UTC, merged